/** 서울 근로장학생 관리 API v4 — 기존 swtm2 데이터에 하위 호환 필드만 추가합니다. */
const DATA_KEY = 'swtm2';
const SESSION_PREFIX = 'sess_';
const SESSION_HOURS = 24;
const TIMEZONE = 'Asia/Seoul';
const PROFILE_PHOTO_FOLDER_KEY = 'swtm_profile_photo_folder';

function doGet(e) { return handle_(request_(e)); }
function doPost(e) { return handle_(request_(e)); }
function request_(e) { const params=(e&&e.parameter)||{};let body={};try{body=e&&e.postData&&e.postData.contents?JSON.parse(e.postData.contents):{};}catch(_){}return Object.assign({},body,params,{action:body.action||params.action||''}); }
function handle_(req) {
  try {
    const routes={
      login:function(){return login_(req.username,req.password);},logout:function(){return logout_(req.token);},session:function(){return loadApp_(req.token);},loadApp:function(){return loadApp_(req.token);},
      adminSaveData:function(){return adminSaveData_(req.token,req.data);},adminUpsertUser:function(){return adminUpsertUser_(req.token,req.user);},adminDeleteUser:function(){return adminDeleteUser_(req.token,req.userId);},
      studentCreateSwap:function(){return studentCreateSwap_(req.token,req.swap);},studentApplySwap:function(){return studentApplySwap_(req.token,req.swapId);},adminUpdateSwap:function(){return adminUpdateSwap_(req.token,req.swapId,req.status,req.note,req.assigneeId);},studentMarkNoticeRead:function(){return studentMarkNoticeRead_(req.token,req.noticeId);},studentUploadProfilePhoto:function(){return studentUploadProfilePhoto_(req.token,req.photo);},getProfilePhoto:function(){return getProfilePhoto_(req.token,req.studentId);},
      adminUpsertExtraJob:function(){return adminUpsertExtraJob_(req.token,req.job);},adminUpdateExtraApplicant:function(){return adminUpdateExtraApplicant_(req.token,req.jobId,req.studentId,req.status);},adminCancelExtraJob:function(){return adminCancelExtraJob_(req.token,req.jobId);},studentApplyExtraJob:function(){return studentApplyExtraJob_(req.token,req.jobId);},studentCancelExtraJob:function(){return studentCancelExtraJob_(req.token,req.jobId);},
      studentCheckIn:function(){return studentCheckIn_(req.token,req.workInstanceId);},studentCheckOut:function(){return studentCheckOut_(req.token,req.workInstanceId);},adminCorrectAttendance:function(){return adminCorrectAttendance_(req.token,req.workInstanceId,req.actualCheckIn,req.actualCheckOut,req.reason);},adminMarkAbsent:function(){return adminMarkAbsent_(req.token,req.workInstanceId,req.reason);},adminRestoreAbsent:function(){return adminRestoreAbsent_(req.token,req.workInstanceId,req.reason);}
    };
    if(!routes[req.action])return respond_({ok:false,error:'알 수 없는 요청입니다.'});
    return respond_(routes[req.action]());
  } catch(err) { return respond_({ok:false,error:err.message||'서버 처리 중 오류가 발생했습니다.'}); }
}
function respond_(payload){return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);}

/** 최초 1회만 실행합니다. 기존 DATA_KEY 값은 절대 덮어쓰지 않습니다. */
function initialize(){const props=PropertiesService.getScriptProperties();if(props.getProperty(DATA_KEY))return '이미 초기화되었습니다.';const password=props.getProperty('INITIAL_ADMIN_PASSWORD');if(!password)throw new Error('INITIAL_ADMIN_PASSWORD를 먼저 설정하세요.');const admin=makeUser_({id:Utilities.getUuid(),username:'admin',name:'서울 총무팀 관리자',role:'admin',active:true},password);saveData_({version:4,students:[],schedules:[],exceptions:[],accounts:[admin],notices:[],handovers:[],swaps:[],extraJobs:[],attendances:[],attendanceAudit:[],semesters:[{id:'semester-2026-2',name:'2026-2학기',startDate:'2026-09-01',endDate:'2027-02-28',active:true,budgets:{general:{total:0,wage:0},holmz:{total:0,wage:0}}}],settings:{activeSemesterId:'semester-2026-2',initializedAt:new Date().toISOString()}});return '초기 관리자 계정이 생성되었습니다.';}

function login_(username,password){const data=data_(),account=data.accounts.find(function(x){return x.username===String(username||'').trim()&&x.active;}),valid=account&&(account.passwordHash?account.passwordHash===hash_(password,account.salt):account.h===legacyHash_(password,account.s));if(!valid)return{ok:false,error:'아이디 또는 비밀번호를 확인하세요.'};validateStudentLink_(data,account);const token=Utilities.getUuid();PropertiesService.getScriptProperties().setProperty(SESSION_PREFIX+token,JSON.stringify({id:account.id,e:Date.now()+SESSION_HOURS*3600000}));return{ok:true,token:token,user:publicUser_(account),data:dataForUser_(data,account)};}
function logout_(token){PropertiesService.getScriptProperties().deleteProperty(SESSION_PREFIX+token);return{ok:true};}
function loadApp_(token){const user=requireUser_(token),data=data_();validateStudentLink_(data,user);return{ok:true,user:publicUser_(user),data:dataForUser_(data,user)};}
function adminSaveData_(token,incoming){const admin=requireAdmin_(token);if(!incoming||!Array.isArray(incoming.students)||!Array.isArray(incoming.schedules))throw new Error('저장할 데이터 형식이 올바르지 않습니다.');const current=data_(),next=normalizeData_(incoming);next.students.forEach(function(student){const saved=current.students.find(function(x){return x.id===student.id;});if(saved&&saved.photoFileId&&!student.photoFileId){student.photoFileId=saved.photoFileId;student.photoUpdatedAt=saved.photoUpdatedAt||'';}});next.accounts=current.accounts;next.swaps=current.swaps;next.extraJobs=current.extraJobs;next.attendances=current.attendances;next.attendanceAudit=current.attendanceAudit;saveData_(next);return{ok:true,data:dataForUser_(next,admin)};}
function adminUpsertUser_(token,incoming){const admin=requireAdmin_(token),data=data_();if(!incoming||!incoming.username||!incoming.name||!incoming.role)throw new Error('이름, 아이디, 역할은 필수입니다.');if(['admin','viewer','student'].indexOf(incoming.role)===-1)throw new Error('올바른 역할을 선택하세요.');if(incoming.role==='student'&&!data.students.some(function(x){return x.id===incoming.studentId&&x.active;}))throw new Error('학생 계정은 활성 학생과 연결해야 합니다.');const studentId=incoming.role==='student'?(incoming.studentId||''):'';let user=data.accounts.find(function(x){return x.id===incoming.id;});if(data.accounts.some(function(x){return(!user||x.id!==user.id)&&x.username===incoming.username;}))throw new Error('이미 사용 중인 아이디입니다.');if(user){Object.assign(user,{username:incoming.username,name:incoming.name,role:incoming.role,studentId:studentId,active:incoming.active!==false});if(incoming.password){user.salt=Utilities.getUuid();user.s=user.salt;user.passwordHash=hash_(incoming.password,user.salt);user.h=user.passwordHash;}}else{if(!incoming.password)throw new Error('새 계정의 초기 비밀번호를 입력하세요.');user=makeUser_({id:Utilities.getUuid(),username:incoming.username,name:incoming.name,role:incoming.role,studentId:studentId,active:incoming.active!==false},incoming.password);data.accounts.push(user);}saveData_(data);return{ok:true,data:dataForUser_(data,admin)};}
function adminDeleteUser_(token,userId){const admin=requireAdmin_(token),data=data_();if(admin.id===userId)throw new Error('현재 로그인한 관리자 계정은 삭제할 수 없습니다.');data.accounts=data.accounts.filter(function(x){return x.id!==userId;});saveData_(data);return{ok:true,data:dataForUser_(data,admin)};}
function withLock_(callback){const lock=LockService.getScriptLock();lock.waitLock(10000);try{return callback();}finally{lock.releaseLock();}}

function studentCreateSwap_(token,incoming){const user=requireStudent_(token),data=data_(),student=studentForUser_(data,user);if(!incoming||!incoming.scheduleId||!incoming.date||!incoming.reason)throw new Error('대상 일정과 사유를 입력하세요.');const schedule=data.schedules.find(function(x){return x.id===incoming.scheduleId&&x.studentId===student.id&&x.site===student.site&&x.semesterId===data.settings.activeSemesterId;});if(!schedule)throw new Error('현재 학기의 본인 근무만 요청할 수 있습니다.');const occurrence=eventsForDate_(data,student.site,incoming.date,data.settings.activeSemesterId,student.id).find(function(x){return x.id===schedule.id;});if(!occurrence||occurrence.isSubstitute)throw new Error('해당 날짜에 본인이 실제 근무자로 지정된 일정이 아닙니다.');if(data.swaps.some(function(x){return x.scheduleId===schedule.id&&x.date===incoming.date&&['반려','취소'].indexOf(x.status)===-1;}))throw new Error('같은 근무에 진행 중인 대타 요청이 있습니다.');data.swaps.unshift({id:Utilities.getUuid(),scheduleId:schedule.id,site:student.site,semesterId:data.settings.activeSemesterId,requesterId:user.id,requesterStudentId:student.id,requesterName:student.name,date:incoming.date,reason:incoming.reason,status:'모집중',applicants:[],assigneeId:'',assigneeName:'',adminNote:'',createdAt:new Date().toISOString()});saveData_(data);return{ok:true,data:dataForUser_(data,user)};}
function studentApplySwap_(token,swapId){const user=requireStudent_(token);return withLock_(function(){const data=data_(),student=studentForUser_(data,user),swap=data.swaps.find(function(x){return x.id===swapId&&x.status==='모집중';});if(!swap)throw new Error('현재 모집 중인 대타가 아닙니다.');if(swap.site!==student.site)throw new Error('다른 근무지의 대타는 신청할 수 없습니다.');if(swap.semesterId!==data.settings.activeSemesterId)throw new Error('현재 학기의 대타만 신청할 수 있습니다.');if(swap.requesterStudentId===student.id)throw new Error('본인 요청에는 신청할 수 없습니다.');swap.applicants=swap.applicants||[];if(swap.applicants.some(function(x){return x.studentId===student.id;}))throw new Error('이미 신청한 대타입니다.');const occurrence=eventsForDate_(data,swap.site,swap.date,swap.semesterId,swap.requesterStudentId).find(function(x){return x.id===swap.scheduleId;});if(!occurrence)throw new Error('대상 근무를 찾을 수 없습니다.');if(hasConflict_(data,student.id,swap.date,occurrence.start,occurrence.end,''))throw new Error('기존 근무와 시간이 겹칩니다.');swap.applicants.push({studentId:student.id,name:student.name,appliedAt:new Date().toISOString()});saveData_(data);return{ok:true,data:dataForUser_(data,user)};});}
function adminUpdateSwap_(token,swapId,status,note,assigneeId){const admin=requireAdmin_(token);return withLock_(function(){const data=data_(),swap=data.swaps.find(function(x){return x.id===swapId;});if(!swap)throw new Error('대타 요청을 찾을 수 없습니다.');if(status==='대타확정'){const assignee=data.students.find(function(x){return x.id===assigneeId&&x.active;}),occurrence=eventsForDate_(data,swap.site,swap.date,swap.semesterId,swap.requesterStudentId).find(function(x){return x.id===swap.scheduleId;});if(!assignee||assignee.site!==swap.site)throw new Error('같은 근무지의 활성 학생만 대타로 확정할 수 있습니다.');if(!(swap.applicants||[]).some(function(x){return x.studentId===assignee.id;}))throw new Error('가져가기를 신청한 학생만 확정할 수 있습니다.');if(!occurrence||hasConflict_(data,assignee.id,swap.date,occurrence.start,occurrence.end,''))throw new Error('대타 학생의 기존 근무와 시간이 겹칩니다.');swap.assigneeId=assignee.id;swap.assigneeName=assignee.name;}else if(status==='반려'){swap.assigneeId='';swap.assigneeName='';}swap.status=status;swap.adminNote=note||'';swap.updatedAt=new Date().toISOString();saveData_(data);return{ok:true,data:dataForUser_(data,admin)};});}

function adminUpsertExtraJob_(token,incoming){const admin=requireAdmin_(token),data=data_();if(!incoming||!incoming.title||!incoming.place||!incoming.date||!incoming.start||!incoming.end||Number(incoming.capacity)<1)throw new Error('구인 정보를 모두 입력하세요.');if(minutes_(incoming.end)<=minutes_(incoming.start))throw new Error('종료시간은 시작시간보다 늦어야 합니다.');if(['general','holmz'].indexOf(incoming.site)===-1)throw new Error('올바른 근무지를 선택하세요.');let job=data.extraJobs.find(function(x){return x.id===incoming.id;});const activeCount=job?(job.applicants||[]).filter(function(a){return a.status!=='CANCELLED'&&a.status!=='REJECTED';}).length:0;if(Number(incoming.capacity)<activeCount)throw new Error('현재 신청자 수보다 모집인원을 줄일 수 없습니다.');const fields={semesterId:data.settings.activeSemesterId,site:incoming.site,title:incoming.title,place:incoming.place,date:incoming.date,start:incoming.start,end:incoming.end,capacity:Number(incoming.capacity),description:incoming.description||'',status:incoming.status==='CLOSED'?'CLOSED':'OPEN',updatedAt:new Date().toISOString()};if(job)Object.assign(job,fields);else{job=Object.assign({id:Utilities.getUuid(),applicants:[],createdAt:new Date().toISOString(),createdBy:admin.id},fields);data.extraJobs.unshift(job);}saveData_(data);return{ok:true,data:dataForUser_(data,admin)};}
function studentApplyExtraJob_(token,jobId){const user=requireStudent_(token);return withLock_(function(){const data=data_(),student=studentForUser_(data,user),job=data.extraJobs.find(function(x){return x.id===jobId;});if(!job||job.status!=='OPEN'||job.semesterId!==data.settings.activeSemesterId)throw new Error('현재 신청 가능한 구인이 아닙니다.');if(job.site!==student.site)throw new Error('다른 근무지의 구인에는 신청할 수 없습니다.');job.applicants=job.applicants||[];if(job.applicants.some(function(a){return a.studentId===student.id&&a.status!=='CANCELLED'&&a.status!=='REJECTED';}))throw new Error('이미 신청한 구인입니다.');const activeCount=job.applicants.filter(function(a){return a.status!=='CANCELLED'&&a.status!=='REJECTED';}).length;if(activeCount>=Number(job.capacity))throw new Error('모집 정원이 마감되었습니다.');if(hasConflict_(data,student.id,job.date,job.start,job.end,''))throw new Error('기존 근무와 시간이 겹칩니다.');job.applicants.push({studentId:student.id,name:student.name,status:'APPLIED',appliedAt:new Date().toISOString()});saveData_(data);return{ok:true,data:dataForUser_(data,user)};});}
function studentCancelExtraJob_(token,jobId){const user=requireStudent_(token);return withLock_(function(){const data=data_(),student=studentForUser_(data,user),job=data.extraJobs.find(function(x){return x.id===jobId&&x.site===student.site;});if(!job||job.status!=='OPEN')throw new Error('모집 중인 구인만 신청 취소할 수 있습니다.');const application=(job.applicants||[]).find(function(a){return a.studentId===student.id&&a.status!=='CANCELLED'&&a.status!=='REJECTED';});if(!application)throw new Error('신청 내역을 찾을 수 없습니다.');if(application.status==='CONFIRMED')throw new Error('관리자가 확정한 추가근무는 취소할 수 없습니다.');application.status='CANCELLED';application.cancelledAt=new Date().toISOString();saveData_(data);return{ok:true,data:dataForUser_(data,user)};});}
function adminUpdateExtraApplicant_(token,jobId,studentId,status){const admin=requireAdmin_(token);return withLock_(function(){const data=data_(),job=data.extraJobs.find(function(x){return x.id===jobId;}),student=data.students.find(function(x){return x.id===studentId&&x.active;});if(!job||!student||student.site!==job.site)throw new Error('구인 또는 같은 근무지 신청자를 찾을 수 없습니다.');const application=(job.applicants||[]).find(function(a){return a.studentId===studentId&&a.status!=='CANCELLED';});if(!application)throw new Error('신청 내역을 찾을 수 없습니다.');if(status==='CONFIRMED'){const confirmed=job.applicants.filter(function(a){return a.status==='CONFIRMED'&&a.studentId!==studentId;}).length;if(confirmed>=Number(job.capacity))throw new Error('확정 정원이 마감되었습니다.');if(hasConflict_(data,student.id,job.date,job.start,job.end,'extra:'+job.id+':'+student.id+':'+job.date))throw new Error('학생의 기존 근무와 시간이 겹칩니다.');}if(['CONFIRMED','REJECTED'].indexOf(status)===-1)throw new Error('올바른 처리 상태가 아닙니다.');application.status=status;application.updatedAt=new Date().toISOString();application.updatedBy=admin.id;saveData_(data);return{ok:true,data:dataForUser_(data,admin)};});}
function adminCancelExtraJob_(token,jobId){const admin=requireAdmin_(token),data=data_(),job=data.extraJobs.find(function(x){return x.id===jobId;});if(!job)throw new Error('구인을 찾을 수 없습니다.');if(job.date<today_()&&data.attendances.some(function(a){return a.sourceType==='extra'&&a.workInstanceId.indexOf('extra:'+job.id+':')===0;}))throw new Error('근태 기록이 있는 지난 구인은 취소할 수 없습니다.');job.status='CANCELLED';job.updatedAt=new Date().toISOString();job.updatedBy=admin.id;saveData_(data);return{ok:true,data:dataForUser_(data,admin)};}

function studentCheckIn_(token,workInstanceId){const user=requireStudent_(token);return withLock_(function(){const data=data_(),student=studentForUser_(data,user),event=resolveWorkInstance_(data,workInstanceId),existing=data.attendances.find(function(a){return a.workInstanceId===workInstanceId;});validateAttendanceOwner_(data,event,student);if(event.workDate!==today_())throw new Error('오늘 근무만 출근 처리할 수 있습니다.');if(existing&&existing.checkoutType==='ABSENT')throw new Error('관리자가 결근 처리한 근무입니다. 관리자에게 문의하세요.');if(existing&&existing.actualCheckIn)throw new Error('이미 출근 처리되었습니다.');const now=new Date().toISOString(),record=Object.assign({},existing||{},{attendanceId:existing?existing.attendanceId:Utilities.getUuid(),workInstanceId:workInstanceId,semesterId:event.semesterId,site:event.site,studentId:event.studentId,scheduleId:event.id,sourceType:event.sourceType,workDate:event.workDate,scheduledStart:event.start,scheduledEnd:event.end,actualCheckIn:now,actualCheckOut:'',checkoutType:'',correctedByAdmin:existing?existing.correctedByAdmin:false,createdAt:existing?existing.createdAt:now,updatedAt:now});data.attendances=data.attendances.filter(function(a){return a.workInstanceId!==workInstanceId;});data.attendances.push(record);saveData_(data);return{ok:true,data:dataForUser_(data,user)};});}
function studentCheckOut_(token,workInstanceId){const user=requireStudent_(token);return withLock_(function(){const data=data_(),student=studentForUser_(data,user),event=resolveWorkInstance_(data,workInstanceId),attendance=data.attendances.find(function(a){return a.workInstanceId===workInstanceId;});validateAttendanceOwner_(data,event,student);if(!attendance||!attendance.actualCheckIn)throw new Error('출근 기록을 찾을 수 없습니다.');if(attendance.actualCheckOut)throw new Error('이미 퇴근 처리되었습니다.');if(event.workDate!==today_())throw new Error('오늘 근무만 퇴근 처리할 수 있습니다.');const now=new Date(),scheduledEnd=dateTime_(event.workDate,event.end);attendance.actualCheckOut=now.toISOString();attendance.checkoutType=now<scheduledEnd?'EARLY_MANUAL':'MANUAL';attendance.updatedAt=attendance.actualCheckOut;saveData_(data);return{ok:true,data:dataForUser_(data,user)};});}
function adminCorrectAttendance_(token,workInstanceId,actualCheckIn,actualCheckOut,reason){
  const admin=requireAdmin_(token),data=data_(),event=resolveWorkInstance_(data,workInstanceId);
  if(!reason)throw new Error('보정 사유를 입력하세요.');
  if(actualCheckOut&&!actualCheckIn)throw new Error('퇴근 기록에는 출근 기록이 필요합니다.');
  if(actualCheckIn&&isNaN(new Date(actualCheckIn).getTime()))throw new Error('올바른 출근시간이 아닙니다.');
  if(actualCheckOut&&isNaN(new Date(actualCheckOut).getTime()))throw new Error('올바른 퇴근시간이 아닙니다.');
  if(actualCheckIn&&actualCheckOut&&new Date(actualCheckOut)<new Date(actualCheckIn))throw new Error('퇴근시간은 출근시간보다 늦어야 합니다.');
  const before=data.attendances.find(function(a){return a.workInstanceId===workInstanceId;}),now=new Date().toISOString(),record=Object.assign({},before||{},{attendanceId:before?before.attendanceId:Utilities.getUuid(),workInstanceId:workInstanceId,semesterId:event.semesterId,site:event.site,studentId:event.studentId,scheduleId:event.id,sourceType:event.sourceType,workDate:event.workDate,scheduledStart:event.start,scheduledEnd:event.end,actualCheckIn:actualCheckIn||'',actualCheckOut:actualCheckOut||'',checkoutType:actualCheckOut?'ADMIN_CORRECTED':'',correctedByAdmin:true,createdAt:before?before.createdAt:now,updatedAt:now});
  data.attendances=data.attendances.filter(function(a){return a.workInstanceId!==workInstanceId;});data.attendances.push(record);
  data.attendanceAudit.push({id:Utilities.getUuid(),attendanceId:record.attendanceId,workInstanceId:workInstanceId,before:before||null,after:record,reason:reason,adminId:admin.id,adminName:admin.name,createdAt:now});
  saveData_(data);return{ok:true,data:dataForUser_(data,admin)};
}

function adminMarkAbsent_(token,workInstanceId,reason){
  const admin=requireAdmin_(token),data=data_(),event=resolveWorkInstance_(data,workInstanceId),now=new Date();
  if(event.workDate!==today_())throw new Error('결근은 당일 근무만 처리할 수 있습니다.');
  if(now<dateTime_(event.workDate,event.start))throw new Error('근무 시작 전에는 결근 처리할 수 없습니다.');
  const existing=data.attendances.find(function(a){return a.workInstanceId===workInstanceId;});
  if(existing&&existing.checkoutType==='ABSENT')throw new Error('이미 결근 처리된 근무입니다.');
  if(existing&&(existing.actualCheckIn||existing.actualCheckOut))throw new Error('출퇴근 기록이 있는 근무는 결근 처리할 수 없습니다.');
  const recordedAt=now.toISOString(),record={attendanceId:existing?existing.attendanceId:Utilities.getUuid(),workInstanceId:workInstanceId,semesterId:event.semesterId,site:event.site,studentId:event.studentId,scheduleId:event.id,sourceType:event.sourceType,workDate:event.workDate,scheduledStart:event.start,scheduledEnd:event.end,actualCheckIn:'',actualCheckOut:'',checkoutType:'ABSENT',correctedByAdmin:false,absenceReason:String(reason||'관리자 결근 처리'),absenceMarkedBy:admin.id,absenceMarkedByName:admin.name,absenceMarkedAt:recordedAt,createdAt:existing?existing.createdAt:recordedAt,updatedAt:recordedAt};
  data.attendances=data.attendances.filter(function(a){return a.workInstanceId!==workInstanceId;});data.attendances.push(record);
  data.attendanceAudit.push({id:Utilities.getUuid(),attendanceId:record.attendanceId,workInstanceId:workInstanceId,before:existing||null,after:record,reason:'결근 처리: '+record.absenceReason,adminId:admin.id,adminName:admin.name,createdAt:recordedAt});
  saveData_(data);return{ok:true,data:dataForUser_(data,admin)};
}

function adminRestoreAbsent_(token,workInstanceId,reason){
  const admin=requireAdmin_(token),data=data_(),event=resolveWorkInstance_(data,workInstanceId),existing=data.attendances.find(function(a){return a.workInstanceId===workInstanceId;});
  if(!existing||existing.checkoutType!=='ABSENT')throw new Error('복구할 결근 기록이 없습니다.');
  const recordedAt=new Date().toISOString();data.attendances=data.attendances.filter(function(a){return a.workInstanceId!==workInstanceId;});
  data.attendanceAudit.push({id:Utilities.getUuid(),attendanceId:existing.attendanceId,workInstanceId:workInstanceId,before:existing,after:null,reason:'결근 취소'+(reason?': '+reason:''),adminId:admin.id,adminName:admin.name,createdAt:recordedAt});
  saveData_(data);return{ok:true,data:dataForUser_(data,admin)};
}

function studentMarkNoticeRead_(token,noticeId){const user=requireStudent_(token),data=data_(),student=studentForUser_(data,user),notice=data.notices.find(function(x){return x.id===noticeId;});if(!notice||notice.semesterId!==data.settings.activeSemesterId||['all',student.site].indexOf(notice.site)===-1)throw new Error('확인할 수 없는 공지입니다.');notice.readBy=notice.readBy||[];if(notice.readBy.indexOf(user.id)===-1)notice.readBy.push(user.id);saveData_(data);return{ok:true};}

function studentUploadProfilePhoto_(token,photo){const user=requireStudent_(token),data=data_(),student=studentForUser_(data,user),dataUrl=String(photo&&photo.dataUrl||''),match=dataUrl.match(/^data:(image\/(?:jpeg|png));base64,([A-Za-z0-9+/=]+)$/i);if(!match)throw new Error('JPG 또는 PNG 사진만 업로드할 수 있습니다.');const bytes=Utilities.base64Decode(match[2]);if(!bytes.length||bytes.length>500000)throw new Error('압축 후 500KB 이하 사진만 업로드할 수 있습니다.');const mime=match[1].toLowerCase(),folder=profilePhotoFolder_(),oldId=student.photoFileId||'',extension=mime==='image/png'?'png':'jpg',file=folder.createFile(Utilities.newBlob(bytes,mime,'student-profile-'+student.id+'.'+extension));student.photoFileId=file.getId();student.photoUpdatedAt=new Date().toISOString();saveData_(data);if(oldId)try{DriveApp.getFileById(oldId).setTrashed(true);}catch(_){}return{ok:true,data:dataForUser_(data,user)};}
function getProfilePhoto_(token,studentId){const user=requireUser_(token),data=data_(),student=data.students.find(function(x){return x.id===studentId&&x.active;});if(!student)throw new Error('학생 정보를 찾을 수 없습니다.');if(user.role!=='admin'&&user.studentId!==student.id)throw new Error('본인 증명사진만 볼 수 있습니다.');if(!student.photoFileId)return{ok:true,dataUrl:''};const blob=DriveApp.getFileById(student.photoFileId).getBlob(),bytes=blob.getBytes();if(bytes.length>500000)throw new Error('사진 파일이 너무 큽니다.');return{ok:true,dataUrl:'data:'+blob.getContentType()+';base64,'+Utilities.base64Encode(bytes)};}
function profilePhotoFolder_(){const props=PropertiesService.getScriptProperties(),id=props.getProperty(PROFILE_PHOTO_FOLDER_KEY);if(id)try{return DriveApp.getFolderById(id);}catch(_){}const folder=DriveApp.createFolder('서울 총무팀 근로장학생 증명사진');props.setProperty(PROFILE_PHOTO_FOLDER_KEY,folder.getId());return folder;}

function normalizeData_(raw){const data=JSON.parse(JSON.stringify(raw||{}));data.version=4;data.settings=data.settings||{};data.semesters=Array.isArray(data.semesters)&&data.semesters.length?data.semesters:[{id:'semester-2026-2',name:'2026-2학기',startDate:'2026-09-01',endDate:'2027-02-28',active:true,budgets:{general:{total:0,wage:0,rates:{}},holmz:{total:0,wage:0,rates:{}}}}];data.semesters.forEach(function(s){s.budgets=s.budgets||{};s.budgets.general=Object.assign({total:0,wage:0,rates:{}},s.budgets.general||{});s.budgets.holmz=Object.assign({total:0,wage:0,rates:{}},s.budgets.holmz||{});});data.settings.activeSemesterId=data.settings.activeSemesterId||(data.semesters.find(function(s){return s.active;})||data.semesters[0]).id;const semesterId=data.settings.activeSemesterId;data.students=(data.students||[]).map(function(s,i){return Object.assign({studentNumber:'',phone:'',email:'',active:true,color:colorFor_(s.id||String(i)),semesterIds:[semesterId]},s);});data.schedules=(data.schedules||[]).map(function(x){return Object.assign({semesterId:semesterId},x);});data.exceptions=(data.exceptions||[]).map(function(x){return Object.assign({semesterId:semesterId},x);});data.notices=(data.notices||[]).map(function(x){return Object.assign({site:'all',important:false,semesterId:semesterId,readBy:[]},x);});data.handovers=(data.handovers||[]).map(function(x){return Object.assign({site:'all',important:false,url:'',semesterId:semesterId},x);});data.swaps=(data.swaps||[]).map(function(x){return Object.assign({applicants:[],semesterId:semesterId},x);});data.extraJobs=(data.extraJobs||[]).map(function(x){return Object.assign({applicants:[],status:'OPEN',description:'',place:'',createdAt:'',createdBy:'',semesterId:semesterId},x);});data.attendances=(data.attendances||[]).map(function(x){return Object.assign({actualCheckIn:'',actualCheckOut:'',checkoutType:'',sourceType:'schedule',correctedByAdmin:false,createdAt:'',updatedAt:''},x);});data.attendanceAudit=Array.isArray(data.attendanceAudit)?data.attendanceAudit:[];data.accounts=data.accounts||[];return data;}
function dataForUser_(data,user){data=normalizeData_(data);if(user.role==='admin')return publicAdminData_(data);if(user.role==='viewer')return publicViewerData_(data);const student=studentForUser_(data,user),site=student.site,semesterId=data.settings.activeSemesterId,semesters=data.semesters.map(function(x){return{id:x.id,name:x.name,startDate:x.startDate,endDate:x.endDate,active:x.active,budgets:{general:{total:0,wage:0},holmz:{total:0,wage:0}}};}),extraJobs=data.extraJobs.filter(function(x){return x.site===site&&x.semesterId===semesterId;}).map(function(x){const safe=Object.assign({},x);safe.applicantCount=(x.applicants||[]).filter(function(a){return a.status!=='CANCELLED'&&a.status!=='REJECTED';}).length;safe.applicants=(x.applicants||[]).filter(function(a){return a.studentId===student.id;});return safe;});return{version:data.version,settings:data.settings,semesters:semesters,students:[safeStudent_(student)],schedules:data.schedules.filter(function(x){return x.site===site&&x.semesterId===semesterId;}),exceptions:data.exceptions.filter(function(x){return x.site===site&&x.semesterId===semesterId;}),notices:data.notices.filter(function(x){return(x.site==='all'||x.site===site)&&x.semesterId===semesterId;}),handovers:data.handovers.filter(function(x){return(x.site==='all'||x.site===site)&&x.semesterId===semesterId;}),swaps:data.swaps.filter(function(x){return x.site===site&&x.semesterId===semesterId;}),extraJobs:extraJobs,attendances:data.attendances.filter(function(x){return x.studentId===student.id&&x.semesterId===semesterId;}),attendanceAudit:[],accounts:[]};}
function publicAdminData_(data){return{version:data.version,settings:data.settings,semesters:data.semesters,students:data.students.map(adminStudent_),schedules:data.schedules,exceptions:data.exceptions,notices:data.notices,handovers:data.handovers,swaps:data.swaps,extraJobs:data.extraJobs,attendances:data.attendances,attendanceAudit:data.attendanceAudit,accounts:data.accounts.map(publicUser_)};}
function publicViewerData_(data){return{version:data.version,settings:data.settings,semesters:data.semesters,students:data.students.map(safeStudent_),schedules:data.schedules,exceptions:data.exceptions,notices:data.notices,handovers:data.handovers,swaps:data.swaps,extraJobs:data.extraJobs,attendances:data.attendances,attendanceAudit:data.attendanceAudit,accounts:[]};}

function eventsForDate_(data,site,date,semesterId,onlyStudentId){const key=typeof date==='string'?date:Utilities.formatDate(date,TIMEZONE,'yyyy-MM-dd'),semester=data.semesters.find(function(s){return s.id===semesterId;});if(semester&&((semester.startDate&&key<semester.startDate)||(semester.endDate&&key>semester.endDate)))return[];const day=dateTime_(key,'12:00').getDay(),exceptions=data.exceptions.filter(function(x){return x.site===site&&x.semesterId===semesterId&&x.date===key;}),regular=data.schedules.filter(function(x){return x.site===site&&x.semesterId===semesterId&&(x.kind==='weekly'?Number(x.weekday)===day:x.date===key);}).reduce(function(all,item){const exception=exceptions.find(function(e){return e.scheduleId===item.id&&e.type!=='add';});if(exception&&exception.type==='cancel')return all;all.push(Object.assign({},item,exception&&exception.type==='change'?{start:exception.start,end:exception.end,exceptionId:exception.id,exceptionType:'change'}:{}));return all;},[]);exceptions.filter(function(x){return x.type==='add';}).forEach(function(x){regular.push({id:x.id,site:x.site,semesterId:x.semesterId,studentId:x.studentId,studentName:x.studentName,kind:'date',date:x.date,start:x.start,end:x.end,exceptionId:x.id,exceptionType:'add'});});const resolved=regular.map(function(item){const swap=data.swaps.find(function(s){return s.scheduleId===item.id&&s.date===key&&s.status==='대타확정'&&s.assigneeId;}),event=swap?Object.assign({},item,{originalStudentId:item.studentId,originalStudentName:item.studentName,studentId:swap.assigneeId,studentName:swap.assigneeName,isSubstitute:true,swapId:swap.id}):item;return Object.assign({},event,{workDate:key,sourceType:'schedule',workInstanceId:'schedule:'+item.id+':'+key});});data.extraJobs.filter(function(job){return job.site===site&&job.semesterId===semesterId&&job.date===key&&job.status!=='CANCELLED';}).forEach(function(job){(job.applicants||[]).filter(function(a){return a.status==='CONFIRMED';}).forEach(function(a){resolved.push({id:'extra:'+job.id,extraJobId:job.id,site:job.site,semesterId:job.semesterId,studentId:a.studentId,studentName:a.name,kind:'date',date:job.date,workDate:key,start:job.start,end:job.end,place:job.place,title:job.title,sourceType:'extra',isExtraWork:true,workInstanceId:'extra:'+job.id+':'+a.studentId+':'+key});});});return resolved.filter(function(x){return!onlyStudentId||x.studentId===onlyStudentId;}).sort(function(a,b){return minutes_(a.start)-minutes_(b.start);});}
function hasConflict_(data,studentId,date,start,end,excludeInstanceId){const student=data.students.find(function(s){return s.id===studentId;});if(!student)return true;return eventsForDate_(data,student.site,date,data.settings.activeSemesterId,studentId).some(function(x){return x.workInstanceId!==excludeInstanceId&&minutes_(start)<minutes_(x.end)&&minutes_(end)>minutes_(x.start);});}
function resolveWorkInstance_(data,workInstanceId){if(!workInstanceId||!/^((schedule)|(extra)):/.test(workInstanceId))throw new Error('올바른 근무 인스턴스가 아닙니다.');const workDate=workInstanceId.slice(-10),events=['general','holmz'].reduce(function(all,site){return all.concat(eventsForDate_(data,site,workDate,data.settings.activeSemesterId,''));},[]),event=events.find(function(x){return x.workInstanceId===workInstanceId;});if(!event)throw new Error('현재 학기의 실제 근무 일정을 찾을 수 없습니다.');return event;}
function validateAttendanceOwner_(data,event,student){if(event.semesterId!==data.settings.activeSemesterId)throw new Error('현재 학기 근무만 처리할 수 있습니다.');if(event.site!==student.site||event.studentId!==student.id)throw new Error('본인이 실제 근무자로 지정된 일정만 처리할 수 있습니다.');}
function minutes_(value){const parts=String(value||'00:00').split(':');return Number(parts[0])*60+Number(parts[1]);}
function dateTime_(date,time){return new Date(date+'T'+time+':00+09:00');}
function today_(){return Utilities.formatDate(new Date(),TIMEZONE,'yyyy-MM-dd');}
function safeStudent_(student){return{id:student.id,name:student.name,site:student.site,type:student.type,active:student.active,color:student.color,semesterIds:student.semesterIds||[],hasProfilePhoto:!!student.photoFileId};}
function adminStudent_(student){const safe=Object.assign({},student,{hasProfilePhoto:!!student.photoFileId});delete safe.photoFileId;return safe;}
function validateStudentLink_(data,user){if(user.role==='student')studentForUser_(data,user);}
function studentForUser_(data,user){const student=data.students.find(function(x){return x.id===user.studentId&&x.active;});if(!student)throw new Error('계정에 연결된 활성 학생 정보가 없습니다.');return student;}
function requireUser_(token){const raw=PropertiesService.getScriptProperties().getProperty(SESSION_PREFIX+token);if(!raw)throw new Error('로그인이 필요하거나 세션이 만료되었습니다.');const session=JSON.parse(raw),expiresAt=session.expiresAt||session.e,userId=session.userId||session.id;if(expiresAt<Date.now()){PropertiesService.getScriptProperties().deleteProperty(SESSION_PREFIX+token);throw new Error('세션이 만료되었습니다. 다시 로그인하세요.');}const user=data_().accounts.find(function(x){return x.id===userId&&x.active;});if(!user)throw new Error('사용할 수 없는 계정입니다.');return user;}
function requireAdmin_(token){const user=requireUser_(token);if(user.role!=='admin')throw new Error('관리자 권한이 필요합니다.');return user;}
function requireStudent_(token){const user=requireUser_(token);if(user.role!=='student')throw new Error('학생 계정만 사용할 수 있습니다.');return user;}
function data_(){const raw=PropertiesService.getScriptProperties().getProperty(DATA_KEY);if(!raw)throw new Error('서버 초기화가 필요합니다.');return normalizeData_(JSON.parse(raw));}
function saveData_(data){PropertiesService.getScriptProperties().setProperty(DATA_KEY,JSON.stringify(normalizeData_(data)));}
function hash_(password,salt){let value=String(password||'')+':'+salt;for(let i=0;i<5000;i++)value=Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value));return value;}
function legacyHash_(password,salt){let value=String(password||'')+salt;for(let i=0;i<2000;i++)value=Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value));return value;}
function makeUser_(fields,password){const salt=Utilities.getUuid(),passwordHash=hash_(password,salt);return Object.assign({},fields,{salt:salt,passwordHash:passwordHash,s:salt,h:passwordHash});}
function publicUser_(user){return{id:user.id,username:user.username,name:user.name,role:user.role,studentId:user.studentId||'',active:user.active};}
function colorFor_(id){const colors=['#2f6f9f','#2d7d74','#7b5ba7','#b8673e','#537e4c','#a34f6f'];let n=0;String(id||'').split('').forEach(function(c){n+=c.charCodeAt(0);});return colors[n%colors.length];}
