/** Student availability, preferences, and administrator draft scheduling. */
function ensurePlanningData_(data){
  data.classSchedules=Array.isArray(data.classSchedules)?data.classSchedules:[];
  data.workPreferences=Array.isArray(data.workPreferences)?data.workPreferences:[];
  data.scheduleDrafts=Array.isArray(data.scheduleDrafts)?data.scheduleDrafts:[];
  data.notices=(data.notices||[]).map(function(n){return Object.assign({requiresRead:false,readBy:[]},n);});
  return data;
}
function assertPlanningTime_(item){if(!item||!validTime_(item.start)||!validTime_(item.end)||minutes_(item.end)<=minutes_(item.start)||minutes_(item.start)%30||minutes_(item.end)%30)throw Error('시간은 30분 단위로 올바르게 입력하세요.');}
function overlaps_(a,b){return minutes_(a.start)<minutes_(b.end)&&minutes_(a.end)>minutes_(b.start);}
function classConflict_(data,studentId,semesterId,date,start,end,excludeId){const weekday=dateTime_(date,'12:00').getDay();return data.classSchedules.some(function(c){return c.id!==excludeId&&c.studentId===studentId&&c.semesterId===semesterId&&Number(c.weekday)===weekday&&overlaps_({start:start,end:end},c);});}
function validatePlanningCandidate_(data,item,excludeDraftId){
  assertPlanningTime_(item);const semester=data.semesters.find(function(s){return s.id===item.semesterId;}),student=data.students.find(function(s){return s.id===item.studentId;});
  if(!semester||!student||student.site!==item.site||!participates_(data,student.id,semester.id,item.date))throw Error('활성 학기 참여 학생과 근무지를 확인하세요.');
  const period=semesterPeriodForDate_(semester,item.date);if([PERIOD_TERM,PERIOD_VACATION].indexOf(period)===-1)throw Error('근무 가능한 학기중 또는 방학중 날짜가 아닙니다.');
  if(period===PERIOD_TERM&&classConflict_(data,student.id,semester.id,item.date,item.start,item.end,''))throw Error('수업시간과 겹칩니다.');
  if(period===PERIOD_VACATION){const hours=vacationHoursForSite_(semester,item.site);if(!hours||minutes_(item.start)<minutes_(hours.start)||minutes_(item.end)>minutes_(hours.end))throw Error('방학 운영시간 밖입니다.');}
  if(hasConflict_(data,student.id,item.date,item.start,item.end,''))throw Error('기존 확정근무·대타·추가근무와 겹칩니다.');
  if(data.scheduleDrafts.some(function(d){return d.id!==excludeDraftId&&d.status==='DRAFT'&&d.studentId===student.id&&d.date===item.date&&overlaps_(d,item);}))throw Error('다른 제작 Draft와 겹칩니다.');
  const probe=copy_(data);probe.schedules.push({id:'planning-probe',semesterId:item.semesterId,site:item.site,studentId:item.studentId,studentName:student.name,periodType:period,kind:'date',date:item.date,start:item.start,end:item.end});
  const violation=operationalViolations_(probe).find(function(v){return v.type==='WEEKLY_LIMIT'&&v.studentId===student.id&&v.semesterId===semester.id;});if(violation)throw Error('주간 최대시간을 초과합니다.');
  return{student:student,semester:semester,period:period};
}
function studentUpsertClassSchedule_(token,item){const user=requireStudent_(token),data=data_(),student=studentForUser_(data,user),old=data.classSchedules.find(function(r){return r.id===item.id;});assertPlanningTime_(item);if(!data.semesters.some(function(s){return s.id===item.semesterId;})||item.semesterId!==data.settings.activeSemesterId)throw Error('현재 학기 수업만 관리할 수 있습니다.');if(old&&old.studentId!==student.id)throw Error('본인 수업만 수정할 수 있습니다.');if(!Number.isInteger(Number(item.weekday))||Number(item.weekday)<0||Number(item.weekday)>6)throw Error('수업 요일을 확인하세요.');if(data.classSchedules.some(function(c){return c.id!==(old&&old.id)&&c.studentId===student.id&&c.semesterId===item.semesterId&&Number(c.weekday)===Number(item.weekday)&&overlaps_(c,item);}))throw Error('수업시간이 겹칩니다.');const next={id:old?old.id:Utilities.getUuid(),studentId:student.id,semesterId:item.semesterId,weekday:Number(item.weekday),start:item.start,end:item.end,subject:String(item.subject||'').trim().slice(0,80),updatedAt:new Date().toISOString()};if(old)data.classSchedules[data.classSchedules.indexOf(old)]=Object.assign({},old,next);else data.classSchedules.push(next);saveData_(data);return{ok:true,data:dataForUser_(data,user)};}
function studentDeleteClassSchedule_(token,itemId){const user=requireStudent_(token),data=data_(),student=studentForUser_(data,user),old=data.classSchedules.find(function(r){return r.id===itemId;});if(!old||old.studentId!==student.id)throw Error('본인 수업만 삭제할 수 있습니다.');data.classSchedules=data.classSchedules.filter(function(r){return r.id!==itemId;});saveData_(data);return{ok:true,data:dataForUser_(data,user)};}
function studentUpsertWorkPreference_(token,item){const user=requireStudent_(token),data=data_(),student=studentForUser_(data,user),old=data.workPreferences.find(function(r){return r.id===item.id;});if(old&&old.studentId!==student.id)throw Error('본인 희망근무만 수정할 수 있습니다.');const next={id:old?old.id:Utilities.getUuid(),studentId:student.id,semesterId:data.settings.activeSemesterId,site:student.site,date:item.date,start:item.start,end:item.end,status:'REQUESTED',updatedAt:new Date().toISOString()};if(data.workPreferences.some(function(r){return r.id!==(old&&old.id)&&r.studentId===student.id&&r.date===next.date&&overlaps_(r,next);}))throw Error('다른 희망근무와 겹칩니다.');const probe=copy_(data);probe.workPreferences=probe.workPreferences.filter(function(r){return r.id!==(old&&old.id)&&r.studentId===student.id&&mondayKey_(r.date)===mondayKey_(next.date);});validatePlanningCandidate_(probe,next,'');const requested=probe.workPreferences.reduce(function(total,r){return total+minutes_(r.end)-minutes_(r.start);},minutes_(next.end)-minutes_(next.start)),semester=data.semesters.find(function(s){return s.id===next.semesterId;}),period=semesterPeriodForDate_(semester,next.date),limit=Number(period===PERIOD_VACATION?semester.vacationWeeklyLimit:semester.termWeeklyLimit)*60;if(requested>limit)throw Error('희망근무가 주간 최대시간을 초과합니다.');if(old)data.workPreferences[data.workPreferences.indexOf(old)]=Object.assign({},old,next);else data.workPreferences.push(next);saveData_(data);return{ok:true,data:dataForUser_(data,user)};}
function studentDeleteWorkPreference_(token,itemId){const user=requireStudent_(token),data=data_(),student=studentForUser_(data,user),old=data.workPreferences.find(function(r){return r.id===itemId;});if(!old||old.studentId!==student.id)throw Error('본인 희망근무만 취소할 수 있습니다.');data.workPreferences=data.workPreferences.filter(function(r){return r.id!==itemId;});saveData_(data);return{ok:true,data:dataForUser_(data,user)};}
function adminUpsertScheduleDraft_(token,item){const admin=requireAdmin_(token),data=data_(),old=data.scheduleDrafts.find(function(r){return r.id===item.id;});if(old&&old.status==='CONFIRMED')throw Error('확정된 Draft는 변경할 수 없습니다.');const next={id:old?old.id:Utilities.getUuid(),studentId:item.studentId,semesterId:item.semesterId,site:item.site,date:item.date,start:item.start,end:item.end,status:'DRAFT',updatedBy:admin.id,updatedAt:new Date().toISOString()};validatePlanningCandidate_(data,next,old&&old.id);if(old)data.scheduleDrafts[data.scheduleDrafts.indexOf(old)]=Object.assign({},old,next);else data.scheduleDrafts.push(next);saveData_(data);return{ok:true,data:dataForUser_(data,admin)};}
function adminDeleteScheduleDraft_(token,itemId){const admin=requireAdmin_(token),data=data_(),old=data.scheduleDrafts.find(function(r){return r.id===itemId;});if(!old||old.status!=='DRAFT')throw Error('삭제 가능한 Draft가 아닙니다.');data.scheduleDrafts=data.scheduleDrafts.filter(function(r){return r.id!==itemId;});saveData_(data);return{ok:true,data:dataForUser_(data,admin)};}
function adminConfirmScheduleDraft_(token,itemId){const admin=requireAdmin_(token),data=data_(),draft=data.scheduleDrafts.find(function(r){return r.id===itemId;});if(!draft||draft.status!=='DRAFT')throw Error('확정 가능한 Draft가 아닙니다.');const checked=validatePlanningCandidate_(data,draft,draft.id),schedule={id:Utilities.getUuid(),semesterId:draft.semesterId,site:draft.site,studentId:draft.studentId,studentName:checked.student.name,periodType:checked.period,kind:'date',date:draft.date,start:draft.start,end:draft.end,createdFromDraftId:draft.id,createdAt:new Date().toISOString()};data.schedules.push(schedule);draft.status='CONFIRMED';draft.scheduleId=schedule.id;draft.confirmedBy=admin.id;draft.confirmedAt=new Date().toISOString();saveData_(data);return{ok:true,data:dataForUser_(data,admin)};}
function planningCandidates_(data,site,semesterId,date,start,end){return data.students.filter(function(s){if(s.site!==site||!participates_(data,s.id,semesterId,date))return false;try{validatePlanningCandidate_(data,{studentId:s.id,semesterId:semesterId,site:site,date:date,start:start,end:end},'');return true;}catch(_){return false;}}).map(function(s){const wanted=data.workPreferences.some(function(p){return p.studentId===s.id&&p.semesterId===semesterId&&p.date===date&&minutes_(p.start)<=minutes_(start)&&minutes_(p.end)>=minutes_(end);}),week=weeklyPolicyState_(data,data.semesters.find(function(t){return t.id===semesterId;}))[mondayKey_(date)],minutes=week&&week.students[s.id]?Object.values(week.students[s.id]).reduce(function(a,b){return a+b;},0):0;return{studentId:s.id,name:s.name,wanted:wanted,hours:minutes/60,reason:wanted?'희망시간 일치 · 충돌 없음':'공강 · 충돌 없음'};}).sort(function(a,b){return Number(b.wanted)-Number(a.wanted)||a.hours-b.hours||a.name.localeCompare(b.name);});}
